export const USER_EMAIL_STATE_CHANGE="USER_EMAIL_STATE_CHANGE";
export const USER_USERNAME_STATE_CHANGE="USER_USERNAME_STATE_CHANGE";
export const USER_FULLNAME_STATE_CHANGE="USER_FULLNAME_STATE_CHANGE";
export const USER_PASSWORD_STATE_CHANGE="USER_PASSWORD_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";
